package com.github.lppedd.idea.pomsky.lang.lexer;

import com.github.lppedd.idea.pomsky.lang.PomskyLanguage;
import com.intellij.psi.tree.IElementType;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;

/**
 * A subset of tokens used by the Pomsky lexer.
 * <p>
 * The other tokens get generated by Grammar-Kit using {@code pomsky.bnf} definitions.
 *
 * @author Edoardo Luppi
 */
public class PomskyTokenType extends IElementType {
  /**
   * A comment start with {@code #} and end at the end of the same line.
   */
  public static final IElementType COMMENT = new PomskyTokenType("COMMENT");

  /**
   * Symbols: {@code let}, {@code lazy}, {@code range}
   */
  public static final IElementType KEYWORD = new PomskyTokenType("KEYWORD");

  public PomskyTokenType(@NonNls @NotNull final String debugName) {
    super(debugName, PomskyLanguage.INSTANCE);
  }
}
