package com.github.lppedd.idea.pomsky.lang.lexer;

import com.github.lppedd.idea.pomsky.lang.PomskyLanguage;
import com.intellij.psi.tree.IElementType;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;

/**
 * Tokens used by the Pomsky lexer, generated by Grammar-Kit using {@code pomsky.bnf} tokens.
 *
 * @author Edoardo Luppi
 */
public class PomskyTokenType extends IElementType {
  public PomskyTokenType(@NonNls @NotNull final String debugName) {
    super(debugName, PomskyLanguage.INSTANCE);
  }
}
