package com.github.lppedd.idea.pomsky.lang.parser;

import com.github.lppedd.idea.pomsky.lang.PomskyLanguage;
import com.intellij.psi.tree.IElementType;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;

/**
 * Elements used by the Pomsky parser, generated by Grammar-Kit using {@code pomsky.bnf} definitions.
 * <p>
 * An element is created by analyzing the Pomsky tokens returned by the lexer.
 *
 * @author Edoardo Luppi
 * @see com.github.lppedd.idea.pomsky.lang.lexer.PomskyTokenType
 */
public class PomskyElementType extends IElementType {
  public PomskyElementType(@NonNls @NotNull final String debugName) {
    super(debugName, PomskyLanguage.INSTANCE);
  }
}
